export const UPDATE_STEP_INFO = 'UPDATE_STEP_INFO';
export const GO_BACK = 'GO_BACK';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FORM_VALIDATION_FAILED = 'FORM_VALIDATION_FAILED';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
