export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const UPDATE_FORM = 'UPDATE_FORM';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const FORM_VALIDATION_FAILED = 'FORM_VALIDATION_FAILED';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FORM_SUBMISSION_SUCCESS = 'FORM_SUBMISSION_SUCCESS';
export const FORM_SUBMISSION_FAILED = 'FORM_SUBMISSION_FAILED';
export const LOAD_PREVIOUS_STEP_DATA = 'LOAD_PREVIOUS_STEP_DATA';
